name: example
description: Example for todo_extractor.
version: 1.0.1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  todo_extractor: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
