name: todo_extractor
description: Script for fetch your TODO marks.
version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  glob: ^2.1.1
  args: ^2.3.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
