name: todo_extractor
description: This package will allow you to pull your TODOs into a independent file in the root directory.
version: 1.0.1
repository: https://github.com/kirillvikhlyaev/todo_extractor

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  glob: ^2.1.1
  args: ^2.3.1
  file: ^6.1.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
